### ISSUE TITLE
Help Testing

### ISSUE THREAD

**Issue by Oldbikes** [qmarco/TSDZ2-Smart-EBike-compatible-with-original-VlCD6-display#1]
@qmarco 
HI
I am interested in testing this software with existing VLCD5 display, but need help in understanding the actual steps I need to do so.
Are you willing to discuss with me? If so how best, on here or via email?
Thanks for your help

**Comment by MikeFreiberger** [comment]
Oldbikes, I got the code loaded on my TSDZ2 and I'm using the VLCD5. I can help you if needed.

qmarco, I'll post here in Issues if I find anything wrong or interesting.

**Comment by Oldbikes** [comment]
Thanks Mike
I have made progress with the software and am now following on endless-sphere.
I am now on version 0.18.E with configurator 0.3.3

**Comment by MikeFreiberger** [comment]
@Oldbikes , My turn to ask for help then!  I don't see the 0.18.E and configurator 0.3.3 posted in the code revisions here.  Did qmarco move to another repository or site?  Thanks!

**Comment by qmarco** [comment]
Hello!
Temporarily I'm working on an Italian forum ... soon I will release a firmware version M0.18.I and the java configurator 0.3.5.
Many implementations have been introduced ... for the moment follow me here:

http://www.jobike.it/forum/topic.asp?TOPIC_ID=76426&whichpage=25

**Comment by Oldbikes** [comment]
Hi qmarco
Thank you, I am already following your work on that site. My user name there is grecoa :)
My parents are Italian (from Sicilia, near zappan!) I live in England. I speak Italian/Sicilian and read Italian but my writing in italian is not very good :( 
Angelo

**Comment by qmarco** [comment]
Ahhh ok Grecoa.... nice to met you!!
